/*
* generated by Xtext
*/
package org.eclipse.xtext.example.qls.ui.contentassist;

import org.eclipse.xtext.example.qls.ui.contentassist.AbstractQlsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QlsDslProposalProvider extends AbstractQlsDslProposalProvider {

}
