/*
* generated by Xtext
*/
package org.eclipse.xtext.example.ql.ui.contentassist;

import org.eclipse.xtext.example.ql.ui.contentassist.AbstractQlDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QlDslProposalProvider extends AbstractQlDslProposalProvider {

}
