/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.qls;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QlsDslRuntimeModule extends org.eclipse.xtext.example.qls.AbstractQlsDslRuntimeModule {

}
