/*
* generated by Xtext
*/
package org.eclipse.xtext.example.ql.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class QlDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
