/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.ql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QlDslUiModule extends org.eclipse.xtext.example.ql.ui.AbstractQlDslUiModule {
	public QlDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
