/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.qls.scoping;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping on
 * how and when to use it
 * 
 */
public class QlsDslScopeProvider extends QlsDslScopeProviderXtend {

}
