/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.qls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QlsDslUiModule extends org.eclipse.xtext.example.qls.ui.AbstractQlsDslUiModule {
	public QlsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
