/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.ql;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QlDslRuntimeModule extends org.eclipse.xtext.example.ql.AbstractQlDslRuntimeModule {

}
